[package]
name = "openterm-app"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
iced.workspace = true
openterm-core = { path = "../openterm-core" }
openterm-config = { path = "../openterm-config" }
openterm-crypto = { path = "../openterm-crypto" }
openterm-ssh = { path = "../openterm-ssh" }
openterm-storage = { path = "../openterm-storage" }
openterm-terminal = { path = "../openterm-terminal" }
openterm-ui = { path = "../openterm-ui" }
tokio.workspace = true
rfd.workspace = true
libc.workspace = true
syntect = { version = "5.2", default-features = false, features = ["default-syntaxes", "default-themes", "regex-fancy"] }
once_cell = "1.20"
